### ISSUE TITLE
Frontend 테마 upload

### ISSUE THREAD

**Issue by bjsystems** [bjsystems/mottotravel#1]

**Comment by jaemok0514** [comment]
설치 방법 : mottotravel 설치 후 frontend에서 npm install
![image](https://user-images.githubusercontent.com/94815900/160577203-4ec61af4-7f30-40c2-b5d9-a1f6ceb9a39b.png) <br />

그 후 npm run dev로 실행
![image](https://user-images.githubusercontent.com/94815900/160577344-66831e22-bb80-4b9c-9ea9-82e67b330cd1.png)<br />

frontend 주소 : localhost:8087

**Comment by jaemok0514** [comment]
## 테마 적용
![image](https://user-images.githubusercontent.com/94815900/160578231-0dd73ca3-2cbd-47ed-b351-ad322084457e.png)
